### ISSUE TITLE
enable query of COHD as clinical data set

### ISSUE THREAD

**Issue by andrewsu** [biothings/bte_schema#19]
The Translator program has produced three clinical resources -- [COHD](http://cohd.io/about.html), [ICEES](https://researchsoftwareinstitute.github.io/data-translator/apps/icees), and [JHU Clinical profiles](https://model.clinicalprofiles.org/clinicalprofile.html). After quick glance, it seems to me that the COHD is the one that would be easiest to adapt to BTE because the API is relatively simple and well-documented (and it is already [registered in smartAPI](https://smart-api.info/registry?q=cohd)).  To my knowledge, no other Translator tool incorporates these or other clinical sources, so would be a nice distinguishing factor if BTE could...

**Comment by kevinxin90** [comment]
Got it! Will add that soon..

**Comment by kevinxin90** [comment]
COHD has been added: https://github.com/biothings/bte_schema/blob/master/biothings_explorer/config.py#L371
